### 
GET  http://localhost:5277/6/balance

###
POST http://localhost:5277/login
Content-Type: application/json

{
    "username": "admin",
    "password": "password"
}

###
POST http://localhost:5277/test
Content-Type: application/json

{
  
}

###
GET http://localhost:5277/1/accountdetails
Content-Type: application/json
